DELETE FROM menu_items;
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-001','food','burger','برگر','کلاسیک برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، کاهو، خیارشور، گوجه، سیب',0,1);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-002','food','burger','برگر','اسپایسی برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، فلفل هالوپینو، کاهو، خیارشور، گوجه، سیب، پنیر گودا',0,2);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-003','food','burger','برگر','کارامِلایز برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، پیاز کارامل، پیاز حلقه‌ای، کاهو، خیارشور، گوجه، سیب، پنیر گودا',0,3);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-004','food','burger','برگر','چیز برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، کاهو، خیارشور، گوجه، سیب، پنیر گودا',0,4);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-005','food','burger','برگر','بیکن برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، ۱ ورق بیکن گوشت، کاهو، خیارشور، گوجه، سیب، پنیر گودا',0,5);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-006','food','burger','برگر','چیکن برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، ۱ عدد فیله، کاهو، خیارشور، گوجه، سیب، پنیر گودا',0,6);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-007','food','burger','برگر','ماشروم برگر','۱۵۰ گرم برگر دست‌ساز، نان شرکتی، سس قارچ، کاهو، خیارشور، گوجه، سیب',0,7);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-008','food','food-category-8','رویال کامبو','رویال کامبو','۱۵۰ گرم برگر دست‌ساز، ۲ عدد نان تست‌شده، ۳ تکه فیله، دورچین و گارنیش',0,8);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-009','food','nachos','ناچوز','ناچوز مرغ','چیپس، فیله مرغ، تاپینگ دلخواه، سس انتخابی',0,9);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-010','food','nachos','ناچوز','ناچوز گوشت','چیپس، گوشت، تاپینگ دلخواه، سس انتخابی',0,10);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-011','food','nachos','ناچوز','ناچوز میکس','چیپس، فیله مرغ، گوشت، تاپینگ دلخواه، سس انتخابی',0,11);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-012','food','pasta','پاستا','پنه آلفردو','پنه، سس آلفردو، قارچ، گارنیش',0,12);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-013','food','pasta','پاستا','چیکن آلفردو','پنه، سس آلفردو، تکه فیله، گارنیش',0,13);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-014','food','fries','سیب زمینی','فرنچ فرایز','۳۰۰ گرم سیب‌زمینی شرکتی',0,14);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-015','food','fries','سیب زمینی','سیب آلفردو','سیب‌زمینی شرکتی، سس آلفردو، قارچ، گارنیش',0,15);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-016','food','fries','سیب زمینی','سیب آلفردو اسپشیال','سیب‌زمینی شرکتی، سس آلفردو، ۱ عدد فیله، قارچ، گارنیش',0,16);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-017','food','fries','سیب زمینی','سیب بیکن','سیب‌زمینی شرکتی، ۲ ورق بیکن گوشت، دیپ چدار، گارنیش',0,17);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('food-018','food','salad','سالاد','سالاد سزار','۱ تکه فیله، کاهو پیچ، ۲ عدد نان تست‌شده، خردل، گوجه گیلاسی، زیتون سیاه',0,18);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-001','drinks','coffee','کافی','قهوه','',0,1);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-002','drinks','coffee','کافی','اسپرسو تک','',0,2);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-003','drinks','coffee','کافی','اسپرسو دبل','',0,3);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-004','drinks','coffee','کافی','امریکانو','',0,4);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-005','drinks','coffee','کافی','کاپوچینو','',0,5);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-006','drinks','coffee','کافی','شیر نسکافه','',0,6);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-007','drinks','coffee','کافی','لته بیسکویت','',0,7);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-008','drinks','coffee','کافی','لته ماکیاتو','',0,8);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-009','drinks','coffee','کافی','لته','',0,9);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-010','drinks','cold-drinks','نوشیدنی سرد','لیموناد','',0,10);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-011','drinks','cold-drinks','نوشیدنی سرد','رد ولوت','',0,11);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-012','drinks','cold-drinks','نوشیدنی سرد','پینوکولا','',0,12);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-013','drinks','cold-drinks','نوشیدنی سرد','موهیتو','',0,13);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-014','drinks','cold-drinks','نوشیدنی سرد','رد موهیتو','',0,14);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-015','drinks','cold-drinks','نوشیدنی سرد','گلدن بری','',0,15);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-016','drinks','cold-drinks','نوشیدنی سرد','بلو اسکای','',0,16);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-017','drinks','hot-drinks','نوشیدنی گرم','هات چاکلت','',0,17);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-018','drinks','hot-drinks','نوشیدنی گرم','پینک چاکلت','',0,18);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-019','drinks','hot-drinks','نوشیدنی گرم','هات فندوق','',0,19);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-020','drinks','hot-drinks','نوشیدنی گرم','شیر بیسکویت','',0,20);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-021','drinks','hot-drinks','نوشیدنی گرم','شیر عسل','',0,21);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-022','drinks','hot-drinks','نوشیدنی گرم','چای دمی','',0,22);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-023','drinks','hot-drinks','نوشیدنی گرم','چای ماسالا','',0,23);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-024','drinks','hot-drinks','نوشیدنی گرم','چای کرک','',0,24);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-025','drinks','matcha','ماچا اسپرولینا','آیس اسپرولینا لته','',0,25);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-026','drinks','matcha','ماچا اسپرولینا','آیس ماچا لته','',0,26);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-027','drinks','matcha','ماچا اسپرولینا','اسپرولینا لته','',0,27);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-028','drinks','matcha','ماچا اسپرولینا','ماچا لته','',0,28);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-029','drinks','shakes','شیک','وانیل','',0,29);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-030','drinks','shakes','شیک','شکلات','',0,30);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-031','drinks','shakes','شیک','نوتلا','',0,31);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-032','drinks','shakes','شیک','لوتوس','',0,32);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-033','drinks','shakes','شیک','توت فرنگی','',0,33);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-034','drinks','shakes','شیک','موز و شکلات','',0,34);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-035','drinks','shakes','شیک','بادام زمینی','',0,35);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-036','drinks','cold-bar','بار سرد','آیس امریکانو','',0,36);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-037','drinks','cold-bar','بار سرد','آیس ماکیاتو','',0,37);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-038','drinks','cold-bar','بار سرد','آیس رومانو','',0,38);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-039','drinks','cold-bar','بار سرد','آیس لته','',0,39);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-040','drinks','cold-bar','بار سرد','آفوگاتو کلاسیک','',0,40);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-041','drinks','cold-bar','بار سرد','آفوگاتو لوتوس','',0,41);
INSERT INTO menu_items (id,menu_type,category_id,category_name,name,description,price,sort_order) VALUES ('drinks-042','drinks','cold-bar','بار سرد','آفوگاتو نوتلا','',0,42);
